description: A new Flutter project.
name: flutter_starter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.3
  google_fonts: ^2.1.0
  flutter_bloc: ^7.0.1
  injectable: ^1.4.1
  equatable: ^2.0.3
  lint: ^1.5.3
  get_it:

dev_dependencies:
  injectable_generator: ^1.4.1
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/lang/